const dummyPlayerData = [
  {
    id: '1',
    name: 'Player 1',
    shareValue: '1500.54',
    recentChange: '+9.75%',
    imageUrl: 'https://via.placeholder.com/150',
    team: 'Team A',
    age: 28,
    position: 'Forward',
    goals: 30,
    availableShares: 100,
    soldShares: 50,
    sharePrice: 1500.54,
    isIncrease: true,
  },
  {
    id: '2',
    name: 'Player 2',
    shareValue: '1230.45',
    recentChange: '-6.85%',
    imageUrl: 'https://via.placeholder.com/150',
    team: 'Team B',
    age: 25,
    position: 'Midfielder',
    goals: 20,
    availableShares: 120,
    soldShares: 60,
    sharePrice: 1230.45,
    isIncrease: false,
  },
  {
    id: '3',
    name: 'Player 3',
    shareValue: '1000.00',
    recentChange: '+3.45%',
    imageUrl: 'https://via.placeholder.com/150',
    team: 'Team A',
    age: 32,
    position: 'Defender',
    goals: 15,
    availableShares: 80,
    soldShares: 40,
    sharePrice: 1000.00,
    isIncrease: true,
  },
  {
    id: '4',
    name: 'Player 4',
    shareValue: '800.75',
    recentChange: '-3.75%',
    imageUrl: 'https://via.placeholder.com/150',
    team: 'Team B',
    age: 27,
    position: 'Goalkeeper',
    goals: 5,
    availableShares: 150,
    soldShares: 75,
    sharePrice: 800.75,
    isIncrease: false,
  }
];

export default dummyPlayerData;
