const dummyDataActivities = [
  {
    id: '1',
    name: 'Activity 1',
    price: '500.54',
    recentChange: '+9.75%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: true,
    totalShares: 1000,
    availableShares: 450,
    sellingShares: 50,
  },
  {
    id: '2',
    name: 'Activity 2',
    price: '723.45',
    recentChange: '-6.85%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: false,
    totalShares: 2000,
    availableShares: 1500,
    sellingShares: 100,
  },
  {
    id: '3',
    name: 'Activity 3',
    price: '1000.45',
    recentChange: '+3.45%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: true,
    totalShares: 800,
    availableShares: 350,
    sellingShares: 75,
  },
  {
    id: '4',
    name: 'Activity 4',
    price: '876.32',
    recentChange: '-2.14%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: false,
    totalShares: 1500,
    availableShares: 750,
    sellingShares: 120,
  },
];

export default dummyDataActivities;
