const dummyDataTeams = [
  {
    id: '1',
    name: 'Team 1',
    shareValue: '500.54',
    recentChange: '+9.75%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: true,
    league: 'Premier League',
    season: '2023/2024',
    goals: 45,
    wins: 14,
    losses: 3,
  },
  {
    id: '2',
    name: 'Team 2',
    shareValue: '723.45',
    recentChange: '-6.85%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: false,
    league: 'La Liga',
    season: '2023/2024',
    goals: 38,
    wins: 12,
    losses: 5,
  },
  {
    id: '3',
    name: 'Team 3',
    shareValue: '1000.45',
    recentChange: '+3.45%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: true,
    league: 'Bundesliga',
    season: '2023/2024',
    goals: 50,
    wins: 16,
    losses: 2,
  },
  {
    id: '4',
    name: 'Team 4',
    shareValue: '876.32',
    recentChange: '-2.14%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: false,
    league: 'Serie A',
    season: '2023/2024',
    goals: 42,
    wins: 13,
    losses: 4,
  },
  {
    id: '5',
    name: 'Team 5',
    shareValue: '1500.98',
    recentChange: '+1.75%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: true,
    league: 'EPL',
    season: '2023/2024',
    goals: 55,
    wins: 15,
    losses: 2,
  },
  {
    id: '6',
    name: 'Team 6',
    shareValue: '987.65',
    recentChange: '-5.32%',
    imageUrl: 'https://via.placeholder.com/150',
    isIncrease: false,
    league: 'Ligue 1',
    season: '2023/2024',
    goals: 47,
    wins: 14,
    losses: 3,
  },
];

export default dummyDataTeams;
