const dummyBets = [
  {
    id: '1',
    name: 'Weekend Football',
    status: 'Active',
    people: 5,
    numberOfTeams: 2,
    dateCreated: '2024-06-10',
    allocatedAmount: '$100',
    remainingAmount: '$50',
    outcome: '+$150',
    fixtures: [
      {
        id: '1',
        league: 'Premier League',
        leagueIcon: 'https://example.com/leagueIcon1.jpg',
        teamAIcon: 'https://example.com/teamAIcon1.jpg',
        teamBIcon: 'https://example.com/teamBIcon1.jpg',
        time: '20:00',
        multipliers: {
          teamA: '1.5',
          draw: '3.0',
          teamB: '2.5',
        },
      },
      {
        id: '2',
        league: 'Serie A',
        leagueIcon: 'https://example.com/leagueIcon2.jpg',
        teamAIcon: 'https://example.com/teamAIcon2.jpg',
        teamBIcon: 'https://example.com/teamBIcon2.jpg',
        time: '19:00',
        multipliers: {
          teamA: '1.8',
          draw: '2.8',
          teamB: '2.6',
        },
      },
      {
        id: '3',
        league: 'Bundesliga',
        leagueIcon: 'https://example.com/leagueIcon3.jpg',
        teamAIcon: 'https://example.com/teamAIcon3.jpg',
        teamBIcon: 'https://example.com/teamBIcon3.jpg',
        time: '17:00',
        multipliers: {
          teamA: '2.2',
          draw: '2.6',
          teamB: '1.8',
        },
      },
    ],
  },
  {
    id: '2',
    name: 'Champions League',
    status: 'Pending',
    people: 10,
    numberOfTeams: 4,
    dateCreated: '2024-06-08',
    allocatedAmount: '$200',
    remainingAmount: '$0',
    outcome: '+$200',
    fixtures: [
      {
        id: '2',
        league: 'La Liga',
        leagueIcon: 'https://example.com/leagueIcon2.jpg',
        teamAIcon: 'https://example.com/teamAIcon2.jpg',
        teamBIcon: 'https://example.com/teamBIcon2.jpg',
        time: '18:00',
        multipliers: {
          teamA: '1.7',
          draw: '3.2',
          teamB: '2.1',
        },
      },
      {
        id: '3',
        league: 'Europa League',
        leagueIcon: 'https://example.com/leagueIcon3.jpg',
        teamAIcon: 'https://example.com/teamAIcon3.jpg',
        teamBIcon: 'https://example.com/teamBIcon3.jpg',
        time: '15:00',
        multipliers: {
          teamA: '2.0',
          draw: '2.9',
          teamB: '2.3',
        },
      },
    ],
  },
  {
    id: '3',
    name: 'World Cup Finals',
    status: 'Completed',
    people: 15,
    numberOfTeams: 2,
    dateCreated: '2024-06-01',
    allocatedAmount: '$500',
    outcome: '+$300',
    fixtures: [
      {
        id: '3',
        league: 'Bundesliga',
        leagueIcon: 'https://example.com/leagueIcon3.jpg',
        teamAIcon: 'https://example.com/teamAIcon3.jpg',
        teamBIcon: 'https://example.com/teamBIcon3.jpg',
        time: '16:00',
        multipliers: {
          teamA: '1.8',
          draw: '3.1',
          teamB: '2.4',
        },
      },
      {
        id: '4',
        league: 'Serie A',
        leagueIcon: 'https://example.com/leagueIcon2.jpg',
        teamAIcon: 'https://example.com/teamAIcon2.jpg',
        teamBIcon: 'https://example.com/teamBIcon2.jpg',
        time: '17:00',
        multipliers: {
          teamA: '2.2',
          draw: '2.6',
          teamB: '1.8',
        },
      },
    ],
  },
];

export default dummyBets;
