const dummyUser = {
  name: 'John Doe',
  avatar: 'https://example.com/avatar.jpg',
  status: 'Online',
  virtualMoney: 500,
  realMoney: 1500,
  winRate: 0.75,
  totalBets: 20,
  totalWins: 15,
  totalLosses: 5,
  totalEarnings: 2000,
  losses: 100,
  profits: 100,
  totalPredictions: 25,
  subscriptions: 50,
  reBets: 30,
  bettings: 10,
  playerShares: 5,
  teamShares: 5,
  invested: 300,
  p2pSent: 100,
  p2pReceived: 200,
};

export default dummyUser;
