import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0A',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: '#151515',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    marginHorizontal: 10,
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    zIndex: 2,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#E0E0E0',
    fontFamily: 'Roboto-Bold',
  },
  menuButton: {
    marginLeft: 20,
  },
  menu: {
    position: 'absolute',
    top: 60,
    right: 20,
    borderRadius: 10,
    padding: 10,
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    zIndex: 3,
  },
  menuItem: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
    backgroundColor: '#1A1A1A',
    marginBottom: 5,
    transition: 'background-color 0.3s',
    borderWidth: 0.5,
    borderColor: '#3498db',
  },
  menuItemText: {
    color: '#E0E0E0',
    fontSize: 16,
  },
  menuItemActive: {
    backgroundColor: '#3498db',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#0A0A0A',
    zIndex: 1,
  },
  section: {
    padding: 20,
    marginBottom: 20,
    backgroundColor: '#121212',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    marginHorizontal: 10,
  },
  coinsSection: {
    marginTop: 20,
    backgroundColor: '#121212',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 10,
  },
  coinsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  coinBox: {
    flex: 1,
    alignItems: 'flex-start',
    padding: 10,
  },
  coinBoxRight: {
    flex: 1,
    alignItems: 'flex-end',
    padding: 10,
  },
  coinTitle: {
    fontSize: 15,
    color: '#FFFFFF',
    marginTop: 5,
    fontWeight: 'bold',
  },
  coinAmount: {
    fontSize: 12,
    color: '#3498db',
    fontStyle: 'italic',
  },
  coinActions: {
    flexDirection: 'column',
    marginTop: 10,
  },
  claimButton: {
    borderWidth: 1,
    borderColor: '#3498db',
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderRadius: 5,
    marginBottom: 10,
  },
  rechargeButton: {
    borderWidth: 1,
    borderColor: '#3498db',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
  },
  coinButtonText: {
    color: '#3498db',
    fontWeight: 'bold',
    fontFamily: 'Roboto-Medium',
  },
  activityBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    marginBottom: 10,
    backgroundColor: '#151515',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
    transition: 'background-color 0.3s',
  },
  activityBoxActive: {
    backgroundColor: '#1A1A1A',
  },
  activityTitle: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 10,
    fontWeight: 'bold',
    fontFamily: 'Roboto-Medium',
  },
  activitySubtitle: {
    fontSize: 12,
    color: '#AAAAAA',
    marginLeft: 10,
    fontFamily: 'Roboto-Regular',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  statsBox: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    margin: 2,
    backgroundColor: '#151515',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
  },
  statsValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 5,
    fontFamily: 'Roboto-Bold',
  },
  statsLabel: {
    fontSize: 12,
    color: '#AAAAAA',
    fontFamily: 'Roboto-Regular',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 5,
  },
  divider: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    marginHorizontal: 20,
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 5,
    backgroundColor: '#1E88E5',
  },
  horizontalLine: {
    width: '90%',
    height: 1,
    backgroundColor: '#1E88E5',
    marginHorizontal: 5,
  },
  dropdown: {
    position: 'absolute',
    bottom: 60,
    left: '50%',
    transform: [{translateX: -100}],
    backgroundColor: '#151515',
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: '#3498db',
    padding: 10,
    width: 200,
    zIndex: 1,
  },
  dropdownItem: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 0.5,
    borderBottomColor: '#3498db',
  },
  dropdownItemText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
});

export default styles;
