const bets = [
    {
      name: 'Chelsea',
      slogan: 'Exciting match',
      category: 'Soccer',
      teamCount: 5,
      peopleBetted: 100,
      isFull: false,
      subscribers: 150,
      scores: '225',
      closingTime: '2024-05-30 18:00',
      remainingBalance: 500,
      totalBalance: 1000,
      logo: null,
      isAdmin: true,
    },
    {
      name: 'Bet 2',
      slogan: 'Thrilling game',
      category: 'Soccer',
      teamCount: 4,
      peopleBetted: 80,
      isFull: false,
      subscribers: 120,
      scores: '89-92',
      closingTime: '2024-05-30 20:00',
      remainingBalance: 300,
      totalBalance: 1000,
      logo: null,
      isAdmin: false,
    },
    {
      name: 'Bet 3',
      slogan: 'Stunning match',
      category: 'Soccer',
      teamCount: 6,
      peopleBetted: 120,
      isFull: false,
      subscribers: 180,
      scores: '100-95',
      closingTime: '2024-05-31 16:00',
      remainingBalance: 200,
      totalBalance: 1000,
      logo: null,
      isAdmin: false,
    },
    {
      name: 'Bet 4',
      slogan: 'Unforgettable match',
      category: 'Soccer',
      teamCount: 5,
      peopleBetted: 140,
      isFull: false,
      subscribers: 160,
      scores: '92-88',
      closingTime: '2024-05-31 14:00',
      remainingBalance: 100,
      totalBalance: 1000,
      logo: null,
      isAdmin: false,
    },
    {
      name: 'Bet 5',
      slogan: 'Amazing match',
      category: 'Soccer',
      teamCount: 6,
      peopleBetted: 160,
      isFull: false,
      subscribers: 180,
      scores: '98-90',
      closingTime: '2024-05-31 12:00',
      remainingBalance: 50,
      totalBalance: 1000,
      logo: null,
      isAdmin: false,
    },
    {
      name: 'Bet 6',
      slogan: 'Excellent match',
      category: 'Soccer',
      teamCount: 4,
      peopleBetted: 100,
      isFull: false,
      subscribers: 150,
      scores: '85-87',
      closingTime: '2024-05-31 10:00',
      remainingBalance: 200,
      totalBalance: 1000,
      logo: null,
      isAdmin: false,
    },
    {
      name: 'Bet 7',
      slogan: 'Fantastic match',
      category: 'Soccer',
      teamCount: 5,
      peopleBetted: 120,
      isFull: false,
      subscribers: 180,
      scores: '102-98',
      closingTime: '2024-05-31 08:00',
      remainingBalance: 50,
      totalBalance: 1000,
      logo: null,
      isAdmin: false,
    },
    {
      name: 'Bet 8',
      slogan: 'Superb match',
      category: 'Soccer',
      teamCount: 6,
      peopleBetted: 140,
      isFull: false,
      subscribers: 160,
      scores: '96-94',
      closingTime: '2024-05-31 06:00',
      remainingBalance: 100,
      totalBalance: 1000,
      logo: null,
      isAdmin: false,
    },
    {
      name: 'Bet 9',
      slogan: 'Brilliant match',
      category: 'Soccer',
      teamCount: 4,
      peopleBetted: 100,
      isFull: false,
      subscribers: 150,
      scores: '85-87',
      closingTime: '2024-05-31 04:00',
      remainingBalance: 200,
      totalBalance: 1000,
      logo: null,
      isAdmin: false,
    }
  ];


  export default bets;