import generateAvatarUrl from '../../utils/generateAvatarUrl';

const bets = [
  {
    id: '1',
    name: 'Champions',
    owner: 'John Doe',
    avatar: generateAvatarUrl('Champions'),
    league: 'Premier League',
    leagueIcon: generateAvatarUrl('Premier League'),
    teams: 'Liverpool vs. Man United',
    time: '19:00',
    multipliers: {teamA: '1.5', draw: '2', teamB: '2.8'},
    balance: 500,
    totalBalance: 1000,
    isFull: false,
    details: [
      '1: Liverpool win *1.5',
      '2: Draw *2',
      '3: Man United win *2.8',
      '4: Over 2.5 Goals *1.8',
      '5: Under 2.5 Goals *1.8',
    ],
    teamAIcon: generateAvatarUrl('Liverpool'),
    teamBIcon: generateAvatarUrl('Man United'),
    slogan: 'Exciting match',
    category: 'Soccer',
    fixtures: 5,
    peopleBetted: 100,
    viewers: 150,
    allocated: 500,
    available: 1000,
    highestBet: 100,
    lowestBet: 10,
    averageBet: 55,
    postedAt: '2024-05-30 12:00',
    firstFixture: '2024-05-30 16:00',
    lastFixture: '2024-05-30 18:00',
    cashOut: true,
    logo: generateAvatarUrl('Champions'),
    isAdmin: true,
    clonedCount: 20,
    visitedCount: 300,
  },
  {
    id: '2',
    name: 'Bet 2',
    avatar: generateAvatarUrl('Bet 2'),
    league: 'Some League',
    leagueIcon: generateAvatarUrl('Some League'),
    teams: 'Team A vs. Team B',
    time: '18:00',
    multipliers: {teamA: '1.8', draw: '2.5', teamB: '3.0'},
    balance: 300,
    totalBalance: 1000,
    isFull: false,
    details: [
      '1: Team A win *1.8',
      '2: Draw *2.5',
      '3: Team B win *3.0',
    ],
    teamAIcon: generateAvatarUrl('Team A'),
    teamBIcon: generateAvatarUrl('Team B'),
    slogan: 'Thrilling game',
    category: 'Soccer',
    fixtures: 4,
    peopleBetted: 80,
    viewers: 120,
    allocated: 300,
    available: 1000,
    highestBet: 80,
    lowestBet: 20,
    averageBet: 50,
    postedAt: '2024-05-30 14:00',
    firstFixture: '2024-05-30 18:00',
    lastFixture: '2024-05-30 20:00',
    cashOut: true,
    logo: generateAvatarUrl('Bet 2'),
    isAdmin: false,
    clonedCount: 15,
    visitedCount: 250,
  },
  {
    id: '3',
    name: 'Bet 3',
    avatar: generateAvatarUrl('Bet 3'),
    league: 'Another League',
    leagueIcon: generateAvatarUrl('Another League'),
    teams: 'Team C vs. Team D',
    time: '14:00',
    multipliers: {teamA: '2.0', draw: '2.2', teamB: '3.1'},
    balance: 200,
    totalBalance: 1000,
    isFull: false,
    details: [
      '1: Team C win *2.0',
      '2: Draw *2.2',
      '3: Team D win *3.1',
    ],
    teamAIcon: generateAvatarUrl('Team C'),
    teamBIcon: generateAvatarUrl('Team D'),
    slogan: 'Stunning match',
    category: 'Soccer',
    fixtures: 6,
    peopleBetted: 120,
    viewers: 180,
    allocated: 200,
    available: 1000,
    highestBet: 90,
    lowestBet: 15,
    averageBet: 52.5,
    postedAt: '2024-05-31 10:00',
    firstFixture: '2024-05-31 14:00',
    lastFixture: '2024-05-31 16:00',
    cashOut: false,
    logo: generateAvatarUrl('Bet 3'),
    isAdmin: false,
    clonedCount: 18,
    visitedCount: 220,
  },
  {
    id: '4',
    name: 'Bet 4',
    avatar: generateAvatarUrl('Bet 4'),
    league: 'Last League',
    leagueIcon: generateAvatarUrl('Last League'),
    teams: 'Team E vs. Team F',
    time: '16:00',
    multipliers: {teamA: '1.7', draw: '2.3', teamB: '2.9'},
    balance: 150,
    totalBalance: 1000,
    isFull: false,
    details: [
      '1: Team E win *1.7',
      '2: Draw *2.3',
      '3: Team F win *2.9',
    ],
    teamAIcon: generateAvatarUrl('Team E'),
    teamBIcon: generateAvatarUrl('Team F'),
    slogan: 'Unforgettable game',
    category: 'Soccer',
    fixtures: 3,
    peopleBetted: 60,
    viewers: 100,
    allocated: 150,
    available: 1000,
    highestBet: 70,
    lowestBet: 10,
    averageBet: 45,
    postedAt: '2024-05-31 12:00',
    firstFixture: '2024-05-31 16:00',
    lastFixture: '2024-05-31 18:00',
    cashOut: true,
    logo: generateAvatarUrl('Bet 4'),
    isAdmin: false,
    clonedCount: 22,
    visitedCount: 270,
  },
  {
    id: '5',
    name: 'Bet 4',
    avatar: generateAvatarUrl('Bet 4'),
    league: 'Last League',
    leagueIcon: generateAvatarUrl('Last League'),
    teams: 'Team E vs. Team F',
    time: '16:00',
    multipliers: {teamA: '1.7', draw: '2.3', teamB: '2.9'},
    balance: 150,
    totalBalance: 1000,
    isFull: false,
    details: [
      '1: Team E win *1.7',
      '2: Draw *2.3',
      '3: Team F win *2.9',
    ],
    teamAIcon: generateAvatarUrl('Team E'),
    teamBIcon: generateAvatarUrl('Team F'),
    slogan: 'Unforgettable game',
    category: 'Soccer',
    fixtures: 3,
    peopleBetted: 60,
    viewers: 100,
    allocated: 150,
    available: 1000,
    highestBet: 70,
    lowestBet: 10,
    averageBet: 45,
    postedAt: '2024-05-31 12:00',
    firstFixture: '2024-05-31 16:00',
    lastFixture: '2024-05-31 18:00',
    cashOut: true,
    logo: generateAvatarUrl('Bet 4'),
    isAdmin: false,
    clonedCount: 22,
    visitedCount: 270,
  }

];

export default bets;
