import {StyleSheet, Platform} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    marginHorizontal: -10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconWithBadge: {
    position: 'relative',
    marginLeft: 20,
  },
  badge: {
    position: 'absolute',
    right: -4,
    top: -4,
    backgroundColor: 'red',
    borderRadius: 8,
    padding: 2,
    minWidth: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  notificationButton: {},
  chatButton: {},
  createBetButton: {
    borderWidth: 2,
    borderColor: 'green',
    backgroundColor: 'green',
    paddingVertical: 6,
    paddingHorizontal: 13,
    borderRadius: 10,
  },
  createBetButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: 'bold',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 10,
    marginHorizontal: 10,
    paddingHorizontal: 15,
    height: 40,
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    color: '#E0E0E0',
    fontSize: 16,
    marginLeft: 10,
  },
  categoryList: {
    flex: 1,
  },
  categoryContainer: {
    marginBottom: 20,
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#151515',
    borderRadius: 10,
    paddingHorizontal: 15,
    borderWidth: Platform.OS === 'android' ? 1 : 1,
    borderColor: '#3498db',
  },
  categoryTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#3498db',
  },
  categoryIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  categoryIcon: {
    marginLeft: 10,
  },
  betCountContainer: {
    backgroundColor: '#3498db',
    borderRadius: 10,
    paddingVertical: 2,
    paddingHorizontal: 8,
    marginLeft: 10,
  },
  betCountText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 10,
  },
  betsList: {
    paddingLeft: 20,
    marginTop: 10,
  },
  mostViewedSection: {
    marginHorizontal: 10,
    marginBottom: 20,
    backgroundColor: '#000000',
    borderRadius: 10,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    paddingBottom: 15,
    marginTop: 30,
    borderWidth: Platform.OS === 'android' ? 2 : 2,
    borderColor: '#3498db',
    paddingTop: 15,
    paddingHorizontal: 5,
  },
  mostViewedHeaderContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: -12,
    left: '33%',
    right: '33%',
    zIndex: 1,
    backgroundColor: '#000000',
    borderWidth: 2,
    borderColor: '#3498db',
    borderRadius: 10,
  },
  mostViewedTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#3498db',
    backgroundColor: '#000000',
    paddingHorizontal: 5,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 5,
  },
  dropdown: {
    position: 'absolute',
    bottom: 60,
    left: '50%',
    transform: [{translateX: -100}],
    backgroundColor: '#151515',
    borderRadius: 10,
    borderWidth: Platform.OS === 'android' ? 1 : 1,
    borderColor: '#3498db',
    padding: 10,
    width: 200,
    zIndex: 1,
  },
  dropdownItem: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: Platform.OS === 'android' ? 1 : 1,
    borderBottomColor: '#3498db',
  },
  dropdownItemText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
});

export default styles;
