const dummySavedBets = [
  {
    id: '1',
    name: 'Weekend Football',
    date: '2024-07-20',
    amount: '$100',
    outcome: '$150',
    teams: '2',
    fixtures: [
      {
        id: '1',
        leagueIcon: 'https://via.placeholder.com/20',
        league: 'Premier League',
        teamAIcon: 'https://via.placeholder.com/30',
        teamA: 'Liverpool',
        teamBIcon: 'https://via.placeholder.com/30',
        teamB: 'Man United',
        time: '16:00',
        date: '2024-07-21',
        status: 'Pending',
        oddsLabel: '1X',
      },
      {
        id: '2',
        leagueIcon: 'https://via.placeholder.com/20',
        league: 'Serie A',
        teamAIcon: 'https://via.placeholder.com/30',
        teamA: 'Juventus',
        teamBIcon: 'https://via.placeholder.com/30',
        teamB: 'Atletico Madrid',
        time: '17:00',
        date: '2024-07-23',
        status: 'Lost',
        oddsLabel: '2X',
      },
      {
        id: '3',
        leagueIcon: 'https://via.placeholder.com/20',
        league: 'Bundesliga',
        teamAIcon: 'https://via.placeholder.com/30',
        teamA: 'Bayern Munich',
        teamBIcon: 'https://via.placeholder.com/30',
        teamB: 'Schalke 04',
        time: '19:00',
        date: '2024-07-20',
        status: 'Won',
        oddsLabel: '1X',
      },
    ],
  },
  {
    id: '2',
    name: 'Champions League',
    date: '2024-07-18',
    amount: '$200',
    outcome: '$300',
    teams: '4',
    fixtures: [
      {
        id: '2',
        leagueIcon: 'https://via.placeholder.com/20',
        league: 'Champions League',
        teamAIcon: 'https://via.placeholder.com/30',
        teamA: 'Real Madrid',
        teamBIcon: 'https://via.placeholder.com/30',
        teamB: 'Barcelona',
        time: '18:00',
        date: '2024-07-22',
        status: 'Pending',
        oddsLabel: 'X2',
      },
    ],
  },
];

export default dummySavedBets;
