const dummyBets = [
  {
    id: '1',
    name: 'Weekend Football',
    status: 'Active',
    people: 5,
    numberOfTeams: 2,
    dateCreated: '2024-06-10',
    allocatedAmount: '$100',
    remainingAmount: '$50',
    outcome: '+$150',
    fixtures: [
      {
        id: 'f1',
        leagueIcon: 'https://via.placeholder.com/20',
        league: 'Premier League',
        teamAIcon: 'https://via.placeholder.com/30',
        teamA: 'Liverpool',
        time: '16:00',
        date: '2024-06-12',
        teamBIcon: 'https://via.placeholder.com/30',
        teamB: 'Manchester United',
        status: 'Pending',
        oddsLabel: '1X',
      },
      {
        id: 'f2',
        leagueIcon: 'https://via.placeholder.com/20',
        league: 'La Liga',
        teamAIcon: 'https://via.placeholder.com/30',
        teamA: 'Real Madrid',
        time: '18:00',
        date: '2024-06-12',
        teamBIcon: 'https://via.placeholder.com/30',
        teamB: 'Barcelona',
        status: 'Won',
        oddsLabel: '2X',
      },
    ],
  },
  {
    id: '2',
    name: 'Champions League',
    status: 'Pending',
    people: 10,
    numberOfTeams: 4,
    dateCreated: '2024-06-08',
    allocatedAmount: '$200',
    remainingAmount: '$0',
    outcome: '+$200',
    fixtures: [
      {
        id: 'f3',
        leagueIcon: 'https://via.placeholder.com/20',
        league: 'Champions League',
        teamAIcon: 'https://via.placeholder.com/30',
        teamA: 'Chelsea',
        time: '20:00',
        date: '2024-06-15',
        teamBIcon: 'https://via.placeholder.com/30',
        teamB: 'Bayern Munich',
        status: 'Lost',
        oddsLabel: 'X2',
      },
    ],
  },
];

export default dummyBets;
